[package]
name = "drova_plugins"
version = "0.0.0"
edition = "2021"

[dependencies]
dalet = "1.0.0-pre.28"
url = "2.5.4"
drova_sdk = { path = "../drova_sdk", version = "*" }
tokio-gemini = { version = "0.5.2" }
bytes = "1.10.1"

reqwest = "0.12.5"
mime = "0.3.17"

async-trait = "0.1.88"
